### ISSUE TITLE
TODOs in algebra.tex

### ISSUE THREAD

**Issue by mdbrnowski** [mdbrnowski/notes#2]
### TODOs:

- [x] Dowód twierdzenia 4.14.9 (wyznacznik nie zmieni się, jeśli do wiersza (albo kolumny) dodamy kombinację
liniową pozostałych wierszy (kolumn))
- [x] Dowód twierdzenia 4.20 (rozwinięcie Laplace'a)
- [x] Dowód twierdzenia 4.22 (rząd macierzy transponowanej)
- [x] Dowód twierdzenia 4.29 (rząd a stopień minoru)
- [x] Dowód twierdzenia 4.32.2 (macierz odwrotna obliczana przez macierz dopełnień algebraicznych)
- [x] Dowód faktu 6.10 (układ prawoskrętny)
- [x] Dowód twierdzenia 6.15 (objętość równoległościanu)
- [x] Dowód twierdzenia 7.35 (krotność geometryczna <= algebraiczna)

**Comment by mdbrnowski** [comment]
Partially solved in 163bc49a56d75d8947065f69a8ec9b9dd843de87 (parallelepiped)
